version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - client/node_modules
      - ./client:/client
    expose:
      - 3000
    container_name: client
    stdin_open: true
    environment:
      - REACT_APP_KAKAO_JS_KEY = $REACT_APP_KAKAO_JS_KEY

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - server/node_modules
      - ./server:/server
    expose:
      - 5000
    container_name: server
    environment:
      - MYSQL_HOST = $MYSQL_HOST
      - MYSQL_PORT = $MYSQL_PORT
      - MYSQL_USER = $MYSQL_USER
      - MYSQL_PASSWORD = $MYSQL_PASSWORD
      - MYSQL_DATABASE = $MYSQL_DATABASE

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports: -"3000:80"
