version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - client/node_modules
      - ./client:/client
    expose:
      - 3000
    container_name: client
    stdin_open: true
    env_file: .env

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - server/node_modules
      - ./server:/server
    expose:
      - 5000
    container_name: server
    env_file: .env

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports: -"3000:80"
