name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets. DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: client build and push
      run: |
        docker build -t lcyl/springcookie-client ./client
        docker push lcyl/springcookie-client
    
    - name: server build and push
      run: |
        docker build -t lcyl/springcookie-server ./server
        docker push lcyl/springcookie-server
    
    - name: nginx build and push
      run: |
        docker build -t lcyl/springcookie-nginx ./nginx
        docker push lcyl/springcookie-nginx
      
